# Generated by Django 5.1.5 on 2025-02-03 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
