# Generated by Django 5.1.5 on 2025-02-03 17:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_imagestorage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='publish',
            field=models.DateTimeField(blank=django.utils.timezone.now, default=django.utils.timezone.now),
        ),
    ]
