# Generated by Django 5.1.5 on 2025-02-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_videos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videos",
            name="video",
            field=models.FileField(upload_to="videos/"),
        ),
    ]
