# Generated by Django 5.1.5 on 2025-02-03 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_imagestorage_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagestorage',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 17, 40, 21, 679936, tzinfo=datetime.timezone.utc)),
        ),
    ]
