# Generated by Django 5.1.5 on 2025-02-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_videos_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagesmainpage",
            name="image",
            field=models.ImageField(default=None, upload_to="images/main"),
        ),
    ]
