# Generated by Django 5.1.5 on 2025-02-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_images_delete_imagestorage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="images",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.RemoveField(
            model_name="images",
            name="image_id",
        ),
        migrations.AddField(
            model_name="images",
            name="image",
            field=models.ImageField(default=None, upload_to="images/"),
        ),
    ]
